export const KOTIKIT_MCP_INSTRUCTIONS = `kotikit is currently a lightweight design-first MCP server for designers. Use its tools to help designers define screens, sync/search local Figma design-system data, and create safe Figma drafts. Translate tool JSON into plain language for designers; do not expose tool names, schemas, raw paths, or internal JSON unless the user explicitly asks.

Workflow:
- Prefer the graph facade for new work: use kotikit_flow_list to choose a built-in designer flow, kotikit_start to begin it, kotikit_answer for human-in-the-loop questions, kotikit_continue when a run is not waiting, and kotikit_get_artifact or kotikit_list_artifacts for outputs.
- For setup, use kotikit_doctor first, then kotikit_config_status and kotikit_config_init only when needed.
- For /kotikit-auto or kotikit:auto-style work, ask what the designer wants to make, start the create-screen graph flow, answer graph questions with real designer input, and present the next decision in plain language.
- Do not generate code or scaffold code components. Design-to-code is not part of the kotikit core; if asked, offer to create or refine the Figma design instead.
- Fetch kotikit_get_system_prompt once per session before brainstorm-heavy work that references a systemPromptRef.
- Search first for design-system data, then fetch one exact component by path; never load whole indexes, manifests, icon lists, databases, or design-system directories into context.
- Compose screens before extracting draft components. Use local design-system components, variables, icons, and auto layout first; represent missing reusable structure as screen-draft work and ask after the screen is visible whether the designer wants draft components extracted on the same draft page.
- Before creating or refining a Figma design, ask for the exact target draft page or frame URL and bind it through kotikit_bind_figma_target with pageUrl on the active run. Kotikit resolves copied node URLs to the containing page. Do not reverse-engineer target JSON from old runs. The page name must contain Draft or Drafts, and generated nodes stay inside the kotikit-owned Section for that screen.
- Apply Figma drafts incrementally through official Figma MCP. Fetch the graph apply packet with kotikit_get_artifact, prepare the active transaction with kotikit_prepare_figma_write, confirm the returned pageId/pageName/sectionName before use_figma, apply only that active Figma transaction, read the evidence checklist, run a compact scan of the applied root node, then record preflightId, transactionId, node id, Figma node type, bounds, component refs or componentKey, component source, variable refs, required icon refs, auto-layout metadata, and evidenceSnapshot with kotikit_record_figma_apply. Existing-component checklist items must be actual visible UI instances with the expected local design-system key, not hidden proof nodes or hand-built substitutes. The evidenceSnapshot must come from actual Figma nodes: visible component instances, local DS component/icon keys, layout mode, bounds, visibility, opacity, and compact layout metrics. Do not create every screen state in one opaque Figma write.
- Do not finish Figma work manually when the graph is blocked or waiting for an active transaction. Fix or report the kotikit recovery action; a draft is complete only after the graph reaches a completed state and QA/report artifacts are produced.
- Keep generated frames inside the kotikit canvas plan. State frames must be same-sized, non-overlapping, and placed in the planned grid. If the designer later extracts draft components, place them in the planned draft component zone on the same draft page.
- Use generate_figma_design only when capturing a web page or HTML reference is useful, not for normal kotikit draft composition.
- Use the local kotikit plugin only for variable export when Figma REST variables are unavailable. In that case, call kotikit_bridge_start and give the returned URL instead of asking the user to run terminal bridge commands.
- When the user's natural-language intent is to share a kotikit bug, improvement, or feature request, generalize the context into a public-safe generalized maintainer brief and call kotikit_prepare_issue. Do not invoke it automatically after errors. Never include company names, customer data, Figma URLs, file keys, node ids, raw paths, tokens, raw config, logs, graph state dumps, artifact payloads, or generated screen text. The tool returns a GitHub issue preview link for the user to review and submit manually.
- User-facing errors should be the tool's friendly text, without stack traces or extra technical detail.
`;
